.\" Manpage for Jana, an interpreter for the reversible programming language Janus.
.\" Contact kalusn@gmail.com to correct errors or typos in manpage.
.TH JANA 1 "05 April 2013" "2.0" "jana man page"
.SH NAME
jana -- run programs written in Janus.
.SH SYNOPSIS
jana [\fB\-m\fP] [\fB\-t\fP\fIN\fP] [\fB\-i\fP] <file>
.SH DESCRIPTION
Jana is an interpreter for Janus written in haskell. More information about the Janus language can be found in the article at http://dl.acm.org/citation.cfm?id=1244404.
.SH OPTIONS
The options are as follows:
.TP
.BR \-m
Use 32-bit modular integers instead of arbitrary size integers.
.TP
.BR \-t\fIN\fP
Halt program after N seconds with exit code 124.
.TP
.BR \-i
Print inverted program.
.SH SEE ALSO
http://topps.diku.dk/janus-playground
.SH BUGS
No known bugs.
.SH AUTHORS
Michael Budde (mbudde@gmail.com) and Claus Skou Nielsen (kalusn@gmail.com)
